# Generated by Django 4.2.5 on 2023-10-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_open_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="open_answer",
            name="choice_text",
        ),
        migrations.AlterField(
            model_name="open_answer",
            name="votes",
            field=models.TextField(default=0),
        ),
    ]
