# Generated by Django 4.2.5 on 2023-10-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_open_answer_votes_open_answer_user_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="photo_1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="photo_2",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
