# Generated by Django 4.2.5 on 2023-11-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_remove_question_photo_1_remove_question_photo_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="photo_1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="photo_2",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
