# Generated by Django 4.2.5 on 2023-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_question_photo_1_question_photo_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="phone_num",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
