# Generated by Django 4.2.5 on 2023-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_remove_userresponse_selected_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="earing",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.IntegerField(default=0),
        ),
    ]
